name: Continuos integration Workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: circleci/elixir:1.5

    steps:
      - uses: actions/checkout@v1

      - name: Format
        run: mix format --check-formatted

      - name: Install dependencies
        run: mix deps.get

      - name: Runs Tests
        run: mix test
